<?php
require_once __DIR__ . '/api/db.php';
$user=require_login_page('index.php');
if(role_rank($user['role'])<role_rank('moderatore')){header('Location:index.php');exit;}
$roles=array_values(array_filter(ARCADE_ROLES,function($r)use($user){return role_rank($r)<role_rank($user['role']);}));
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Zero World Admin</title>
<link rel="stylesheet" href="assets/css/portal.css"><style>
body{background:#070b14;color:#eef4ff}.admin-wrap{max-width:1500px;margin:auto;padding:20px}.top-admin{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px}.hero{border:1px solid rgba(0,240,255,.25);background:linear-gradient(135deg,rgba(0,240,255,.08),rgba(255,45,107,.07));padding:18px;border-radius:14px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:14px 0}.card{background:rgba(10,16,28,.94);border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:14px}.metric b{display:block;font-size:26px;color:#00f0ff}.tabs{display:flex;flex-wrap:wrap;gap:7px;margin:14px 0}.tab{background:#141d2d;color:#dfe8f5;border:1px solid #273449}.tab.on{background:#0a6070;border-color:#00f0ff}.section{display:none}.section.on{display:block}.table-wrap{overflow:auto;max-height:520px}.t{width:100%;border-collapse:collapse}.t th,.t td{padding:7px 8px;border-bottom:1px solid rgba(255,255,255,.07);text-align:left;font-size:12px;vertical-align:top}.t th{position:sticky;top:0;background:#111a2b}.btn{padding:7px 9px;border-radius:6px;background:#1a2639;color:#fff;border:1px solid #2a3a54}.btn-red{background:#6f1832;border-color:#b52f57}.btn-cyan{background:#0b5362;border-color:#1be9ff}.btn-gold{background:#614d11;border-color:#ffe45b}.form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.form-grid input,.form-grid select,.form-grid textarea{width:100%;padding:9px;border-radius:7px;border:1px solid #2a374e;background:#0b1220;color:#fff}.wide{grid-column:1/-1}.note{color:#9aa7bc;font-size:12px;line-height:1.5}.check{display:flex;gap:8px;align-items:center}.toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.toolbar input,.toolbar select{padding:8px;border-radius:7px;border:1px solid #2a374e;background:#0b1220;color:#fff}.small{font-size:11px}.danger-text{color:#ff6b8f}.ok-text{color:#7dffa9}@media(max-width:1000px){.grid{grid-template-columns:repeat(2,1fr)}.form-grid{grid-template-columns:1fr}}@media(max-width:620px){.grid{grid-template-columns:1fr}.top-admin{align-items:flex-start;flex-direction:column}}
</style></head><body>
<div class="admin-wrap">
<header class="top-admin hero"><div><div style="font-size:12px;color:#7fefff">Zero World CONTROL CENTER</div><h1 style="margin:5px 0 0">Amministrazione completa</h1><div class="note">Account: <b><?=esc($user['username'])?></b> · ruolo <b><?=esc($user['role'])?></b></div></div><div class="toolbar"><a class="btn btn-cyan" href="portal/index.php">← PORTALE</a><a class="btn" href="games/zeroagar_classic.php">ZEROAGAR</a></div></header>
<div id="metrics" class="grid"></div>
<div class="tabs">
<button class="tab on" data-tab="users">👥 Utenti</button><button class="tab" data-tab="games">🎮 Giochi</button><button class="tab" data-tab="progress">📈 Progressi</button><button class="tab" data-tab="rooms">🚪 Stanze</button><button class="tab" data-tab="chat">💬 Chat</button><button class="tab" data-tab="site">⚙ Sistema</button><button class="tab" data-tab="logs">🧾 Audit</button>
</div>
<section id="sec-users" class="section on"><div class="card"><div class="toolbar"><input id="user-q" placeholder="Cerca username o email…"><button class="btn btn-cyan" onclick="loadUsers()">CERCA</button><button class="btn" onclick="createUser()">+ CREA UTENTE</button><button class="btn" onclick="loadUsers()">↻ AGGIORNA</button></div><div class="table-wrap"><table class="t"><thead><tr><th>Utente</th><th>Ruolo</th><th>Economia</th><th>XP/LV</th><th>Stato</th><th>Azioni</th></tr></thead><tbody id="users"></tbody></table></div></div><div class="card"><div class="toolbar"><h3 style="margin-right:auto">Utenti registrati online</h3><button class="btn btn-cyan" onclick="loadOnlineUsers()">↻ AGGIORNA ONLINE</button></div><div class="table-wrap"><table class="t"><thead><tr><th>Utente</th><th>Ruolo</th><th>Email</th><th>Ultima attività</th></tr></thead><tbody id="online-users"></tbody></table></div></div></section>
<section id="sec-games" class="section"><div class="card"><div class="toolbar"><select id="score-game"><option value="">Tutti i giochi</option><option value="zeroagar_classic">ZeroAgar Classic</option><option value="growth_orbit">Growth Orbit</option></select><button class="btn btn-cyan" onclick="loadScores()">CLASSIFICHE</button><button class="btn btn-red" onclick="clearBoard()">SVUOTA CLASSIFICA</button></div><div class="table-wrap"><table class="t"><thead><tr><th>Gioco</th><th>Utente</th><th>Ruolo</th><th>Punteggio</th><th>Data</th><th></th></tr></thead><tbody id="scores"></tbody></table></div></div><div class="card"><h3>Stato giochi</h3><div id="game-flags"></div></div></section>
<section id="sec-progress" class="section"><div class="card"><div class="toolbar"><select id="progress-game"><option value="">Tutti i giochi</option><option value="zeroagar_classic">ZeroAgar Classic</option><option value="growth_orbit">Growth Orbit</option></select><button class="btn btn-cyan" onclick="loadProgress()">CARICA PROGRESSI</button></div><div class="table-wrap"><table class="t"><thead><tr><th>Gioco</th><th>Utente</th><th>Record</th><th>Partite</th><th>Kill</th><th>Tempo</th><th>Ultima massa</th><th></th></tr></thead><tbody id="progress"></tbody></table></div></div></section>
<section id="sec-rooms" class="section"><div class="card"><div class="toolbar"><button class="btn btn-cyan" onclick="loadRooms()">AGGIORNA STANZE</button><button class="btn btn-red" onclick="closeAllRooms()">CHIUDI TUTTE</button></div><div class="table-wrap"><table class="t"><thead><tr><th>ID</th><th>Gioco</th><th>Stato</th><th>P1</th><th>P2</th><th>Turno</th><th></th></tr></thead><tbody id="rooms"></tbody></table></div></div></section>
<section id="sec-chat" class="section"><div class="card"><div class="toolbar"><label for="chat-channel">Canale:</label><select id="chat-channel" onchange="loadChat()"><option value="lobby">Chat portale</option><option value="arena">Chat globale giochi (Arena)</option></select><button class="btn btn-cyan" onclick="loadChat()">AGGIORNA</button><button class="btn btn-red" onclick="clearChat()">SVUOTA CHAT</button></div><div id="chat" style="height:360px;overflow:auto;margin-top:10px"></div></div></section>
<section id="sec-site" class="section"><div class="card"><h3>Impostazioni globali</h3><div class="form-grid"><label class="check"><input type="checkbox" id="maintenance"> Modalità manutenzione</label><label class="check"><input type="checkbox" id="regopen" checked> Registrazioni aperte</label><label class="check"><input type="checkbox" id="gamelock"> Blocca tutti i giochi</label><textarea class="wide" id="announcement" placeholder="Annuncio globale visibile nel portale"></textarea><div><button class="btn btn-gold" onclick="saveSettings()">SALVA IMPOSTAZIONI</button></div></div></div><div class="card"><h3>Manutenzione audit</h3><div class="toolbar"><input id="audit-days" type="number" min="1" value="90"><button class="btn btn-red" onclick="purgeAudit()">ELIMINA AUDIT VECCHI</button></div></div></section>
<section id="sec-logs" class="section"><div class="card"><div class="toolbar"><button class="btn btn-cyan" onclick="loadLogs()">AGGIORNA AUDIT</button></div><div class="table-wrap"><table class="t"><thead><tr><th>Quando</th><th>Staff</th><th>Azione</th><th>Target</th><th>Dettagli</th></tr></thead><tbody id="logs"></tbody></table></div></div></section>
</div>
<script src="assets/js/portal.js"></script><script>
const state={roles:<?=json_encode($roles)?>,rank:<?=role_rank($user['role'])?>};
async function A(body){return api('api/admin.php',body)}
function htmlEsc(v){return esc(v)}
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.getElementById('sec-'+b.dataset.tab).classList.add('on')})}
async function loadStats(){const d=await A({action:'stats'});if(!d.success)return;const s=d.stats;const labels=[['users','Utenti'],['online','Online'],['banned','Bannati'],['staff','Staff'],['scores','Punteggi'],['progress','Progressi'],['rooms','Stanze'],['messages','Chat']];document.getElementById('metrics').innerHTML=labels.map(x=>`<div class="card metric"><div class="note">${x[1]}</div><b>${s[x[0]]}</b></div>`).join('')}
async function loadUsers(){const d=await A({action:'list_users',q:document.getElementById('user-q').value});if(!d.success)return toast(d.error);document.getElementById('users').innerHTML=d.users.map(u=>{const can=u.role && <?=json_encode(array_values(ARCADE_ROLES))?>.indexOf(u.role)<state.rank;let a=can?`<button class="btn btn-red small" onclick="ban('${u.id}',${u.is_banned?0:1})">${u.is_banned?'SBLOCCA':'BAN'}</button> <button class="btn small" onclick="editUser('${u.id}',${u.coins},${u.gems},${u.xp},${u.level},'${htmlEsc(u.clan||'ZERO')}')">MODIFICA</button>`:'';if(can&&state.rank>=<?=role_rank('admin')?>)a+=` <button class="btn small" onclick="setRole('${u.id}')">RUOLO</button> <button class="btn small" onclick="resetPwd('${u.id}')">PASSWORD</button> <button class="btn small" onclick="resetProgress('${u.id}')">RESET</button>`;if(can&&state.rank>=<?=role_rank('founder')?>)a+=` <button class="btn btn-red small" onclick="delUser('${u.id}')">ELIMINA</button>`;return `<tr><td><b>${htmlEsc(u.username)}</b><br><span class="note">${htmlEsc(u.email||'')}<br>${htmlEsc(u.id)}</span></td><td>${htmlEsc(u.role)}</td><td>💰 ${u.coins}<br>💎 ${u.gems}</td><td>XP ${u.xp}<br>LV ${u.level}</td><td class="${u.is_banned?'danger-text':'ok-text'}">${u.is_banned?'BANNATO: '+htmlEsc(u.ban_reason||''):'ATTIVO'}</td><td>${a}</td></tr>`}).join('')}
async function loadOnlineUsers(){const d=await A({action:'online_users'});if(!d.success)return toast(d.error);document.getElementById('online-users').innerHTML=d.users.length?d.users.map(u=>`<tr><td><b>${htmlEsc(u.username)}</b><br><span class="note">${htmlEsc(u.id)}</span></td><td>${htmlEsc(u.role)}</td><td>${htmlEsc(u.email||'—')}</td><td>${htmlEsc(u.last_seen||'')}</td></tr>`).join(''):'<tr><td colspan="4" class="note">Nessun utente registrato online negli ultimi 2 minuti.</td></tr>'}
async function createUser(){const u=prompt('Username nuovo utente:');if(!u)return;const p=prompt('Password/PIN:');if(!p)return;const e=prompt('Email (opzionale):')||'';const r=prompt('Ruolo ('+state.roles.join(', ')+')','user')||'user';const d=await A({action:'create_user',username:u,password:p,email:e,role:r});toast(d.success?'Utente creato':d.error);if(d.success){loadUsers();loadStats()}}
async function ban(id,b){let reason='';if(b){reason=prompt('Motivo ban:')||'';if(!reason)return}const d=await A({action:'set_ban',user_id:id,banned:b,reason});toast(d.success?'Operazione completata':d.error);loadUsers();loadLogs();loadStats()}
async function setRole(id){const r=prompt('Nuovo ruolo: '+state.roles.join(', '));if(!r)return;const d=await A({action:'set_role',user_id:id,role:r});toast(d.success?'Ruolo aggiornato':d.error);loadUsers();loadLogs()}
async function editUser(id,c,g,x,l,clan){const nc=prompt('Monete:',c);if(nc===null)return;const ng=prompt('Gemme:',g);if(ng===null)return;const nx=prompt('XP:',x);if(nx===null)return;const nl=prompt('Livello:',l);if(nl===null)return;const nd=prompt('Clan:',clan);if(nd===null)return;const d=await A({action:'edit_user',user_id:id,coins:+nc,gems:+ng,xp:+nx,level:+nl,clan:nd});toast(d.success?'Utente aggiornato':d.error);loadUsers();loadLogs();loadStats()}
async function resetPwd(id){const p=prompt('Nuova password/PIN:');if(!p)return;const d=await A({action:'reset_password',user_id:id,password:p});toast(d.success?'Password aggiornata':d.error);loadLogs()}
async function resetProgress(id){if(!confirm('Azzerare tutti i progressi di questo utente?'))return;const d=await A({action:'reset_progress',user_id:id,game:''});toast(d.success?'Progressi azzerati':d.error);loadProgress();loadLogs()}
async function delUser(id){if(!confirm('Eliminare definitivamente utente, progressi e punteggi?'))return;const d=await A({action:'delete_user',user_id:id});toast(d.success?'Utente eliminato':d.error);loadUsers();loadStats();loadLogs()}
async function loadScores(){const d=await A({action:'list_scores',game:document.getElementById('score-game').value});if(!d.success)return toast(d.error);document.getElementById('scores').innerHTML=d.scores.map(s=>`<tr><td>${htmlEsc(s.game)}</td><td>${htmlEsc(s.username)}</td><td>${htmlEsc(s.role)}</td><td>${s.score}</td><td>${htmlEsc(s.updated_at)}</td><td><button class="btn btn-red small" onclick="delScore('${s.game}','${s.user_id}')">ELIMINA</button></td></tr>`).join('');loadFlags()}
async function delScore(game,id){const d=await A({action:'delete_score',game,user_id:id});toast(d.success?'Punteggio eliminato':d.error);loadScores();loadLogs()}
async function clearBoard(){const g=document.getElementById('score-game').value;if(!g)return toast('Seleziona un gioco');if(!confirm('Svuotare tutta la classifica '+g+'?'))return;const d=await A({action:'clear_leaderboard',game:g});toast(d.success?'Classifica svuotata':d.error);loadScores();loadStats();loadLogs()}
async function loadProgress(){const d=await A({action:'list_progress',game:document.getElementById('progress-game').value});if(!d.success)return toast(d.error);document.getElementById('progress').innerHTML=d.progress.map(p=>`<tr><td>${htmlEsc(p.game)}</td><td>${htmlEsc(p.username)}</td><td>${p.best_mass}</td><td>${p.games_played}</td><td>${p.total_kills}</td><td>${p.total_time}s</td><td>${p.last_mass}</td><td><button class="btn small" onclick="resetOne('${p.user_id}','${p.game}')">RESET</button></td></tr>`).join('')}
async function resetOne(id,game){if(!confirm('Azzerare il progresso '+game+'?'))return;const d=await A({action:'reset_progress',user_id:id,game});toast(d.success?'Progresso azzerato':d.error);loadProgress();loadLogs()}
async function loadRooms(){const d=await A({action:'rooms_list'});if(!d.success)return toast(d.error);document.getElementById('rooms').innerHTML=d.rooms.map(r=>`<tr><td>#${r.id}</td><td>${htmlEsc(r.game)}</td><td>${htmlEsc(r.status)}</td><td>${htmlEsc(r.p1)}</td><td>${htmlEsc(r.p2||'-')}</td><td>${r.turn}</td><td>${r.status==='waiting'||r.status==='playing'?`<button class="btn btn-red small" onclick="closeRoom(${r.id})">CHIUDI</button>`:''}</td></tr>`).join('')}
async function closeRoom(id){const d=await A({action:'close_room',id});toast(d.success?'Stanza chiusa':d.error);loadRooms();loadStats();loadLogs()}
async function closeAllRooms(){if(!confirm('Chiudere tutte le stanze attive?'))return;const d=await A({action:'close_all_rooms'});toast(d.success?'Stanze chiuse':d.error);loadRooms();loadStats();loadLogs()}
async function loadChat(){const channel=document.getElementById('chat-channel').value;const d=await A({action:'chat_list',channel});if(!d.success)return toast(d.error);document.getElementById('chat').innerHTML=d.messages.map(m=>`<div style="padding:5px;border-bottom:1px solid rgba(255,255,255,.06)"><b>${htmlEsc(m.username)}</b> <span class="note">${htmlEsc(m.created_at)}</span><br>${htmlEsc(m.text)} <button class="btn btn-red small" onclick="delMsg(${m.id})">🗑</button></div>`).join('')||'<div class="note">Nessun messaggio in questo canale.</div>'}
async function delMsg(id){const d=await A({action:'chat_delete',id,channel:document.getElementById('chat-channel').value});toast(d.success?'Messaggio eliminato':d.error);loadChat();loadLogs();loadStats()}
async function clearChat(){if(!confirm('Svuotare tutta la chat selezionata?'))return;const d=await A({action:'chat_clear',channel:document.getElementById('chat-channel').value});toast(d.success?'Chat svuotata':d.error);loadChat();loadLogs();loadStats()}
async function loadSettings(){const d=await A({action:'settings_get'});if(!d.success)return;const s=d.settings||{};document.getElementById('maintenance').checked=s.maintenance==='1';document.getElementById('regopen').checked=s.registration_open!=='0';document.getElementById('gamelock').checked=s.games_locked==='1';document.getElementById('announcement').value=s.announcement||''}
async function saveSettings(){const d=await A({action:'settings_save',maintenance:document.getElementById('maintenance').checked?'1':'0',registration_open:document.getElementById('regopen').checked?'1':'0',games_locked:document.getElementById('gamelock').checked?'1':'0',announcement:document.getElementById('announcement').value});toast(d.success?'Impostazioni salvate':d.error);loadLogs()}
async function loadFlags(){const d=await A({action:'game_flags'});if(!d.success)return;document.getElementById('game-flags').innerHTML=d.games.map(g=>`<div class="card" style="margin:8px 0"><b>${htmlEsc(g.game)}</b><div class="note">Enabled: ${g.enabled?'SI':'NO'} · Maintenance: ${g.maintenance?'SI':'NO'}</div></div>`).join('')}
async function purgeAudit(){const d=await A({action:'purge_audit',days:+document.getElementById('audit-days').value||90});toast(d.success?'Audit pulito':d.error);loadLogs()}
async function loadLogs(){const d=await A({action:'audit_logs'});if(!d.success)return;document.getElementById('logs').innerHTML=d.logs.map(l=>`<tr><td>${htmlEsc(l.created_at)}</td><td>${htmlEsc(l.admin_name)}</td><td>${htmlEsc(l.action)}</td><td>${htmlEsc(l.target)}</td><td>${htmlEsc(l.details)}</td></tr>`).join('')}
tabs();loadStats();loadUsers();loadOnlineUsers();loadScores();loadProgress();loadRooms();loadChat();loadSettings();loadLogs();
</script></body></html>
