<?php
$u = ['username' => 'Giocatore'];
function esc(string $value): string { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Blob Sumo · Zero World</title><style>@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700;800&display=swap');body{margin:0;background:#050814;color:#fff;font-family:Inter,system-ui,sans-serif;overflow:hidden}#app{display:grid;grid-template-columns:1fr 320px;height:100vh}canvas{width:100%;height:100%;display:block;background:#07101f}.side{padding:18px;background:rgba(8,14,31,.96);border-left:1px solid rgba(0,240,255,.25);display:flex;flex-direction:column;gap:10px}.title{font:800 22px Orbitron,sans-serif;color:#00f0ff}.stat{padding:10px;border:1px solid rgba(0,240,255,.2);border-radius:12px;background:#0b1430}.btn{display:block;width:100%;padding:11px;border:0;border-radius:10px;background:#00f0ff;color:#04101b;font-weight:800;cursor:pointer}.btn.alt{background:#1c2b55;color:#fff}.hint{color:#9cb2d9;font-size:13px;line-height:1.5}.lb{max-height:240px;overflow:auto;border:1px solid rgba(255,255,255,.08);border-radius:10px}.row{display:flex;justify-content:space-between;padding:8px 10px;border-bottom:1px solid rgba(255,255,255,.06)}@media(max-width:800px){#app{grid-template-columns:1fr}.side{position:absolute;right:0;top:0;height:100%;width:min(320px,85vw);z-index:5;transform:translateX(100%);transition:.2s}.side.open{transform:translateX(0)}}</style></head>
<body><div id="app"><canvas id="c"></canvas><aside class="side"><div class="title">🤼 Blob Sumo</div><div class="hint">Resisti nel ring e accumula punti per il controllo.</div><div class="stat">Giocatore: <b><span id="name"><?php echo esc($u['username']); ?></span></b></div><div class="stat">Punteggio <b id="score">0</b></div><div class="stat">Record database <b id="best">0</b></div><button class="btn" id="start">GIOCA</button><button class="btn alt" id="back">PORTALE</button><div class="lb" id="lb"></div><div class="hint">Tutti i punteggi vengono salvati su MySQL. Nessun salvataggio locale.</div></aside></div>
<script>
const GAME={slug:"blob_sumo",name:"Blob Sumo"}; const c=document.getElementById('c'),x=c.getContext('2d'); const scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),lb=document.getElementById('lb');
function size(){c.width=Math.max(640,innerWidth-(innerWidth>800?320:0))*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);} addEventListener('resize',size);size();
async function api(action,payload){const r=await fetch('https://games.zerothelegend.com/api/mini_games.php?action='+encodeURIComponent(action),{method:payload?'POST':'GET',credentials:'include',headers:payload?{'Content-Type':'application/json'}:{},body:payload?JSON.stringify(payload):undefined,cache:'no-store'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||('HTTP '+r.status));return d;}
async function loadBoard(){try{const d=await api('leaderboard',null);bestEl.textContent=d.mine||0;lb.innerHTML=(d.top||[]).map(r=>`<div class="row"><span>#${r.rank} ${r.username}</span><b>${r.score}</b></div>`).join('')||'<div class="row">Nessun record</div>';}catch(e){lb.innerHTML='<div class="row">Classifica non disponibile</div>';}}
async function submit(score,stats={}){score=Math.max(0,Math.floor(score));scoreEl.textContent=score;try{const d=await api('submit',{game:GAME.slug,score,stats});bestEl.textContent=d.best||score;}catch(e){console.warn(e);}loadBoard();}
document.getElementById('back').onclick=()=>location.href='https://www.zerothelegend.com/portal/index.php';
let run=false,score=0,px=0,py=0,ox=0,oy=0,t=0;addEventListener('mousemove',e=>{px=e.clientX;py=e.clientY});function start(){run=true;score=0;t=0;px=innerWidth/2;py=innerHeight/2;ox=innerWidth/2+120;oy=innerHeight/2}function f(){if(run){t+=.016;ox=innerWidth/2+Math.cos(t*.9)*Math.min(220,innerWidth*.25);oy=innerHeight/2+Math.sin(t*1.1)*Math.min(140,innerHeight*.2);if(Math.hypot(px-ox,py-oy)<90)score+=1;if(t>20){run=false;submit(score,{seconds:20})}}x.fillStyle='#090d1e';x.fillRect(0,0,innerWidth,innerHeight);x.strokeStyle='#4c5d9f';x.lineWidth=4;x.beginPath();x.arc(innerWidth/2,innerHeight/2,Math.min(250,innerHeight*.3),0,7);x.stroke();x.fillStyle='#00ffa2';x.beginPath();x.arc(px,py,38,0,7);x.fill();x.fillStyle='#ff2d6b';x.beginPath();x.arc(ox,oy,42,0,7);x.fill();requestAnimationFrame(f)}document.getElementById('start').onclick=start;requestAnimationFrame(f);
loadBoard();
</script></body></html>